EXPERIMENT:
  NAME: ""
  TAG: "wkd_f,swin-t,rn18,conv1x1"
  PROJECT: "cifar100_wkd"
  SEED: 10
DISTILLER:
  TYPE: "WKD"
  TEACHER: "swin-t"
  STUDENT: "resnet18"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 300
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
WKD:
  INPUT_SIZE: (224, 224)
  LOSS:
    CE_WEIGHT: 1.0
    WKD_LOGIT_WEIGHT: 0.0
    WKD_FEAT_WEIGHT: 0.008
    COSINE_DECAY_EPOCH: 150
  EPS: 0.00001
  HINT_LAYER: -1
  MEAN_COV_RATIO: 2.0
  PROJECTOR: "conv1x1"
  SPATIAL_GRID: 1
LOG:
  WANDB: True
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 100